server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.25.174:3306/community?serverTimezone=UTC&useUniode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: green
    password: Green1014**##
  jackson:
    date-format: yy-MM-dd HH-mm-ss
    time-zone: GMT+8\