server:
  port: 10000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.25.174:3306/community?serverTimezone=UTC&useUniode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: green
    password: Green1014**##
  jackson:
    date-format: yy-MM-dd HH-mm-ss
    time-zone: GMT+8\
springdoc:
  api-docs:
    #是否开启文档功能
    enabled: true
    #swagger后端请求地址
    path: /api-docs
  swagger-ui:
    #自定义swagger前端请求路径，输入http：127.0.0.1:8080/test会自动重定向到swagger页面
    path: /test
  #包扫描路径
  packages-to-scan: com.herb.plant.community
  #这里定义了两个分组，可定义多个，也可以不定义
  group-configs:
    #分组名
    - group: admin
      #按路径匹配
      pathsToMatch: /article/**
      #分组名
    - group: user
      #按包路径匹配
      packagesToScan: com.hello.api.user


